Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Elias Pereira Lopes
// Descrição   : Tabuada
// Autor(a)    : Elias Lopes
// Data atual  : 24/09/2024
Var
numero, contador, tabuada: inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Qual a tabuada que você deseja?")
leia(numero)
para contador de 0 ate 10 faca
tabuada := numero * contador
escreva(numero, " x ", contador, " = ", tabuada)
fimpara
Fimalgoritmo